### ISSUE TITLE
unknown script 'context.lua' or 'mtx-context.lua'

### ISSUE THREAD

**Issue by ghost** [adityam/context-pkgbuild#3]
when I use setuptex I get following from running context:

``` bash
resolvers       | caches | path '/home/morealaz/texmf-cache' created
mtxrun          | unknown script 'context.lua' or 'mtx-context.lua'
```

but by commenting TEXMFCACHE section in setuptex, context work for me.

**Comment by adityam** [comment]
Just to make sure, you are typing:

```
$source /opt/context-minimals/setuptex
$mtxrun --generate
```

when you get this error?

**Comment by ghost** [comment]
When I run these:

``` bash
$ source /opt/context-minimals/setuptex
$ context --generate
```

I got this error:

``` bash
resolvers       | caches | path '/home/morealaz/texmf-cache' created
mtxrun          | unknown script 'context.lua' or 'mtx-context.lua'
```

but if I run `mtxrun --generate` instead of `context --generate` it runs correctly and make things work.

**Comment by morealaz** [comment]
when I run these:
```bash
$ source /opt/context-minimals/setuptex
$ context --generate
```
I got this error:
```bash
resolvers       | caches | path '/home/morealaz/texmf-cache' created
mtxrun          | unknown script 'context.lua' or 'mtx-context.lua'
```
but if I run `mtxrun --generate` instead of `context --generate`, it runs correctly and without error.

**Comment by adityam** [comment]
I believe that you must have seen `context --generate` step on the wiki. That works for single user installations; for multi user installs, the TEXMFCACHE must be write able by the user. So you need to run `mtxrun ---generate` to initialize the database. 

I am closing this issue because the post install instructions say that you need to run `mtxrun --generate`
